# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Issu.ui',
# licensing of 'Issu.ui' applies.
#
# Created: Sun Sep 22 17:59:32 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Main_Issu(object):
    def setupUi(self, Main_Issu):
        Main_Issu.setObjectName("Main_Issu")
        Main_Issu.resize(1012, 661)
        font = QtGui.QFont()
        Main_Issu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main_Issu.setWindowIcon(icon)
        Main_Issu.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Main_Issu)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 991, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setObjectName("label")
        self.combo_location = QtWidgets.QComboBox(self.frame)
        self.combo_location.setGeometry(QtCore.QRect(94, 15, 150, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.combo_location.setFont(font)
        self.combo_location.setObjectName("combo_location")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.combo_location.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setObjectName("label_2")
        self.button_search = QtWidgets.QPushButton(self.frame)
        self.button_search.setGeometry(QtCore.QRect(900, 10, 75, 41))
        self.button_search.setAutoDefault(True)
        self.button_search.setDefault(True)
        self.button_search.setObjectName("button_search")
        self.input_scname = QtWidgets.QLineEdit(self.frame)
        self.input_scname.setEnabled(True)
        self.input_scname.setGeometry(QtCore.QRect(310, 15, 570, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.input_scname.setFont(font)
        self.input_scname.setAcceptDrops(True)
        self.input_scname.setFrame(True)
        self.input_scname.setDragEnabled(False)
        self.input_scname.setObjectName("input_scname")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 80, 991, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.table_result = QtWidgets.QTableWidget(self.frame_2)
        self.table_result.setGeometry(QtCore.QRect(20, 50, 961, 131))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        self.table_result.setFont(font)
        self.table_result.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_result.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_result.setTabKeyNavigation(True)
        self.table_result.setDragDropOverwriteMode(False)
        self.table_result.setAlternatingRowColors(True)
        self.table_result.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_result.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_result.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.table_result.setShowGrid(True)
        self.table_result.setGridStyle(QtCore.Qt.SolidLine)
        self.table_result.setWordWrap(True)
        self.table_result.setCornerButtonEnabled(True)
        self.table_result.setRowCount(3)
        self.table_result.setColumnCount(6)
        self.table_result.setObjectName("table_result")
        self.table_result.setColumnCount(6)
        self.table_result.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_result.setItem(2, 5, item)
        self.table_result.horizontalHeader().setCascadingSectionResizes(True)
        self.table_result.horizontalHeader().setDefaultSectionSize(120)
        self.table_result.horizontalHeader().setHighlightSections(True)
        self.table_result.horizontalHeader().setSortIndicatorShown(False)
        self.table_result.horizontalHeader().setStretchLastSection(True)
        self.table_result.verticalHeader().setVisible(False)
        self.table_result.verticalHeader().setCascadingSectionResizes(False)
        self.info_result = QtWidgets.QLabel(self.frame_2)
        self.info_result.setGeometry(QtCore.QRect(21, 14, 951, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.info_result.setFont(font)
        self.info_result.setFocusPolicy(QtCore.Qt.NoFocus)
        self.info_result.setObjectName("info_result")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 340, 991, 261))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.table_output = QtWidgets.QTableWidget(self.frame_3)
        self.table_output.setGeometry(QtCore.QRect(10, 10, 961, 241))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        self.table_output.setFont(font)
        self.table_output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_output.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_output.setTabKeyNavigation(True)
        self.table_output.setDragDropOverwriteMode(False)
        self.table_output.setAlternatingRowColors(True)
        self.table_output.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_output.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_output.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_output.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.table_output.setShowGrid(True)
        self.table_output.setGridStyle(QtCore.Qt.SolidLine)
        self.table_output.setWordWrap(True)
        self.table_output.setCornerButtonEnabled(True)
        self.table_output.setRowCount(0)
        self.table_output.setColumnCount(6)
        self.table_output.setObjectName("table_output")
        self.table_output.setColumnCount(6)
        self.table_output.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_output.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_output.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_output.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_output.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_output.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_output.setHorizontalHeaderItem(5, item)
        self.table_output.horizontalHeader().setCascadingSectionResizes(True)
        self.table_output.horizontalHeader().setDefaultSectionSize(120)
        self.table_output.horizontalHeader().setHighlightSections(True)
        self.table_output.horizontalHeader().setSortIndicatorShown(False)
        self.table_output.horizontalHeader().setStretchLastSection(True)
        self.table_output.verticalHeader().setVisible(False)
        self.table_output.verticalHeader().setCascadingSectionResizes(False)
        self.button_del = QtWidgets.QPushButton(self.centralwidget)
        self.button_del.setGeometry(QtCore.QRect(460, 290, 41, 41))
        self.button_del.setObjectName("button_del")
        self.button_insert = QtWidgets.QPushButton(self.centralwidget)
        self.button_insert.setGeometry(QtCore.QRect(510, 290, 41, 41))
        self.button_insert.setObjectName("button_insert")
        self.button_output = QtWidgets.QPushButton(self.centralwidget)
        self.button_output.setGeometry(QtCore.QRect(910, 610, 75, 41))
        self.button_output.setObjectName("button_output")
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setGeometry(QtCore.QRect(830, 610, 75, 41))
        self.button_reset.setObjectName("button_reset")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 619, 191, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setStyleSheet("color: rgb(221, 221, 221);")
        self.label_5.setObjectName("label_5")
        Main_Issu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main_Issu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        Main_Issu.setMenuBar(self.menubar)

        self.retranslateUi(Main_Issu)
        QtCore.QObject.connect(self.button_search, QtCore.SIGNAL("clicked()"), Main_Issu.search)
        QtCore.QObject.connect(self.button_del, QtCore.SIGNAL("clicked()"), Main_Issu.delete)
        QtCore.QObject.connect(self.button_insert, QtCore.SIGNAL("clicked()"), Main_Issu.insert)
        QtCore.QObject.connect(self.button_output, QtCore.SIGNAL("clicked()"), Main_Issu.output)
        QtCore.QObject.connect(self.button_reset, QtCore.SIGNAL("clicked()"), Main_Issu.reset)
        QtCore.QMetaObject.connectSlotsByName(Main_Issu)

    def retranslateUi(self, Main_Issu):
        Main_Issu.setWindowTitle(QtWidgets.QApplication.translate("Main_Issu", "Issu-Education V1.0", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Main_Issu", "시도교육청", None, -1))
        self.combo_location.setCurrentText(QtWidgets.QApplication.translate("Main_Issu", "서울특별시교육청", None, -1))
        self.combo_location.setItemText(0, QtWidgets.QApplication.translate("Main_Issu", "서울특별시교육청", None, -1))
        self.combo_location.setItemText(1, QtWidgets.QApplication.translate("Main_Issu", "부산광역시교육청", None, -1))
        self.combo_location.setItemText(2, QtWidgets.QApplication.translate("Main_Issu", "대구광역시교육청", None, -1))
        self.combo_location.setItemText(3, QtWidgets.QApplication.translate("Main_Issu", "인천광역시교육청", None, -1))
        self.combo_location.setItemText(4, QtWidgets.QApplication.translate("Main_Issu", "광주광역시교육청", None, -1))
        self.combo_location.setItemText(5, QtWidgets.QApplication.translate("Main_Issu", "대전광역시교육청", None, -1))
        self.combo_location.setItemText(6, QtWidgets.QApplication.translate("Main_Issu", "울산광역시교육청", None, -1))
        self.combo_location.setItemText(7, QtWidgets.QApplication.translate("Main_Issu", "세종특별자치시교육청", None, -1))
        self.combo_location.setItemText(8, QtWidgets.QApplication.translate("Main_Issu", "경기도교육청", None, -1))
        self.combo_location.setItemText(9, QtWidgets.QApplication.translate("Main_Issu", "강원도교육청", None, -1))
        self.combo_location.setItemText(10, QtWidgets.QApplication.translate("Main_Issu", "충청북도교육청", None, -1))
        self.combo_location.setItemText(11, QtWidgets.QApplication.translate("Main_Issu", "충청남도교육청", None, -1))
        self.combo_location.setItemText(12, QtWidgets.QApplication.translate("Main_Issu", "전라북도교육청", None, -1))
        self.combo_location.setItemText(13, QtWidgets.QApplication.translate("Main_Issu", "전라남도교육청", None, -1))
        self.combo_location.setItemText(14, QtWidgets.QApplication.translate("Main_Issu", "경상북도교육청", None, -1))
        self.combo_location.setItemText(15, QtWidgets.QApplication.translate("Main_Issu", "경상남도교육청", None, -1))
        self.combo_location.setItemText(16, QtWidgets.QApplication.translate("Main_Issu", "제주도교육청", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Main_Issu", "학교명", None, -1))
        self.button_search.setText(QtWidgets.QApplication.translate("Main_Issu", "검색", None, -1))
        self.table_result.setSortingEnabled(False)
        self.table_result.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Main_Issu", "번호", None, -1))
        self.table_result.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Main_Issu", "학교명", None, -1))
        self.table_result.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Main_Issu", "관할 지역청", None, -1))
        self.table_result.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Main_Issu", "공/사립", None, -1))
        self.table_result.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Main_Issu", "우편번호", None, -1))
        self.table_result.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Main_Issu", "도로명 주소", None, -1))
        __sortingEnabled = self.table_result.isSortingEnabled()
        self.table_result.setSortingEnabled(False)
        self.table_result.setSortingEnabled(__sortingEnabled)
        self.info_result.setText(QtWidgets.QApplication.translate("Main_Issu", "검색 결과", None, -1))
        self.table_output.setSortingEnabled(False)
        self.table_output.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Main_Issu", "번호", None, -1))
        self.table_output.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Main_Issu", "학교명", None, -1))
        self.table_output.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Main_Issu", "관할 지역청", None, -1))
        self.table_output.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Main_Issu", "공/사립", None, -1))
        self.table_output.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Main_Issu", "우편번호", None, -1))
        self.table_output.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Main_Issu", "도로명 주소", None, -1))
        self.button_del.setText(QtWidgets.QApplication.translate("Main_Issu", "∧", None, -1))
        self.button_insert.setText(QtWidgets.QApplication.translate("Main_Issu", "∨", None, -1))
        self.button_output.setText(QtWidgets.QApplication.translate("Main_Issu", "내보내기", None, -1))
        self.button_reset.setText(QtWidgets.QApplication.translate("Main_Issu", "초기화", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Main_Issu", "sihyeon.dev@gmail.com / 이시현", None, -1))

import image_rc
